// setup transformations (fix conflict with ATI_Compressonator)
#define main main_etcpack
#define computeAverageColor2x4noQuantFloat etcpack_computeAverageColor2x4noQuantFloat
#define computeAverageColor4x2noQuantFloat etcpack_computeAverageColor4x2noQuantFloat
#define compressBlockWithTable2x4 etcpack_compressBlockWithTable2x4
#define compressBlockWithTable2x4percep etcpack_compressBlockWithTable2x4percep
#define compressBlockWithTable4x2 etcpack_compressBlockWithTable4x2
#define compressBlockWithTable4x2percep etcpack_compressBlockWithTable4x2percep
#define tryalltables_3bittable2x4 etcpack_tryalltables_3bittable2x4
#define tryalltables_3bittable2x4percep etcpack_tryalltables_3bittable2x4percep
#define tryalltables_3bittable4x2 etcpack_tryalltables_3bittable4x2
#define tryalltables_3bittable4x2percep etcpack_tryalltables_3bittable4x2percep
#define quantize444ColorCombined etcpack_quantize444ColorCombined
#define quantize555ColorCombined etcpack_quantize555ColorCombined
#define quantize444ColorCombinedPerceptual etcpack_quantize444ColorCombinedPerceptual
#define quantize555ColorCombinedPerceptual etcpack_quantize555ColorCombinedPerceptual
#define compressBlockDiffFlipCombined etcpack_compressBlockDiffFlipCombined
#define compressBlockDiffFlipCombinedPerceptual etcpack_compressBlockDiffFlipCombinedPerceptual
#define calcBlockErrorRGB etcpack_calcBlockErrorRGB
#define calcBlockPerceptualErrorRGB etcpack_calcBlockPerceptualErrorRGB
#define write_big_endian_2byte_word etcpack_write_big_endian_2byte_word
#define write_big_endian_4byte_word etcpack_write_big_endian_4byte_word
#define readSrcFile etcpack_readSrcFile
#define readArguments etcpack_readArguments
#define calculateError59Tperceptual1000 etcpack_calculateError59Tperceptual1000
#define compressBlockETC2Fast etcpack_compressBlockETC2Fast
#define compressBlockETC2RGBA1 etcpack_compressBlockETC2RGBA1
#define compressBlockETC2Exhaustive etcpack_compressBlockETC2Exhaustive
#define compressBlockETC2FastPerceptual etcpack_compressBlockETC2FastPerceptual
#define compressBlockETC2ExhaustivePerceptual etcpack_compressBlockETC2ExhaustivePerceptual
#define compressBlockAlphaSlow etcpack_compressBlockAlphaSlow
#define compressBlockAlphaFast etcpack_compressBlockAlphaFast
#define compressBlockAlpha16 etcpack_compressBlockAlpha16
#define compressBlockAlphaSlow etcpack_compressBlockAlphaSlow
#define setupAlphaTableAndValtab etcpack_setupAlphaTableAndValtab
#define readCompressParams etcpack_readCompressParams
#define compressBlockETC1ExhaustivePerceptual etcpack_compressBlockETC1ExhaustivePerceptual
#define compressBlockDiffFlipFast etcpack_compressBlockDiffFlipFast
#define compressBlockDiffFlipFastPerceptual etcpack_compressBlockDiffFlipFastPerceptual
#define compressBlockETC1Exhaustive etcpack_compressBlockETC1Exhaustive
#define compressBlockETC1ExhaustivePerceptual etcpack_compressBlockETC1ExhaustivePerceptual
#define EXHAUSTIVE_CODE_ACTIVE 1

// now include file
#include "source/etcpack.cxx"

// clean up
#undef malloc
#undef free
#undef main
#undef computeAverageColor2x4noQuantFloat
#undef computeAverageColor4x2noQuantFloat
#undef compressBlockWithTable2x4
#undef compressBlockWithTable2x4percep
#undef compressBlockWithTable4x2
#undef compressBlockWithTable4x2percep
#undef tryalltables_3bittable2x4
#undef tryalltables_3bittable2x4percep
#undef tryalltables_3bittable4x2
#undef tryalltables_3bittable4x2percep
#undef quantize444ColorCombined
#undef quantize555ColorCombined
#undef quantize444ColorCombinedPerceptual
#undef quantize555ColorCombinedPerceptual
#undef compressBlockDiffFlipCombined
#undef compressBlockDiffFlipCombinedPerceptual
#undef calcBlockErrorRGB
#undef calcBlockPerceptualErrorRGB
#undef compressBlockDiffFlipFastPerceptual
#undef write_big_endian_2byte_word
#undef write_big_endian_4byte_word
#undef readSrcFile
#undef readArguments 
#undef calculateError59Tperceptual1000 
#undef decompressColor 
#undef compressBlockETC2Fast
#undef compressBlockETC2Exhaustive
#undef compressBlockETC2FastPerceptual
#undef compressBlockETC2ExhaustivePerceptual
#undef compressBlockAlphaSlow
#undef compressBlockAlphaFast
#undef compressBlockAlpha16
#undef compressBlockAlphaSlow
#undef setupAlphaTableAndValtab
#undef readCompressParams
#undef compressBlockETC1ExhaustivePerceptual
#undef compressBlockDiffFlipFast
#undef compressBlockDiffFlipFastPerceptual
#undef compressBlockETC1Exhaustive
#undef compressBlockETC1ExhaustivePerceptual
