#ifndef STANDARD_CONFIG_INCLUDED
#define STANDARD_CONFIG_INCLUDED

#ifdef GL_ES
#define PBR_DIFFUSE 0
#else
#define PBR_DIFFUSE 2
#endif

#define PBR_SPEC_D 2
#define PBR_SPEC_G 3

#define USE_BLINN_PHONG

#define ENABLE_DETAIL_NORMALMAP
#define ENABLE_PARALLAXMAP

#endif
