# This module defines:
# LUAJIT_INCLUDE_DIR, where to find the headers
#
# LUAJIT_LIBRARY
# LUAJIT_FOUND
#

IF (APPLE)
    SET(LUAJIT_LIBDIR "clang")
ELSEIF (CMAKE_COMPILER_IS_GNUCXX)
    SET(LUAJIT_LIBDIR "gcc4")
ELSEIF (MSVC80)
    SET(LUAJIT_LIBDIR "vs2005")
ELSEIF (MSVC90)
    SET(LUAJIT_LIBDIR "vs2008")
ELSEIF (MSVC10)
    SET(LUAJIT_LIBDIR "vs2010")
ELSEIF (MSVC11)
    SET(LUAJIT_LIBDIR "vs2012")
ELSEIF (MSVC12 OR MSVC_VERSION>1800)
    SET(LUAJIT_LIBDIR "vs2013")
ELSEIF (MSVC14 OR MSVC_VERSION>1900)
    SET(LUAJIT_LIBDIR "vs2015")
ENDIF ()

IF (APPLE)
    # do nothing
ELSEIF (CMAKE_CL_64)
    SET(LUAJIT_LIBDIR ${LUAJIT_LIBDIR}/x64)
ELSEIF (CMAKE_COMPILER_IS_GNUCXX AND CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(LUAJIT_LIBDIR ${LUAJIT_LIBDIR}/x64)
ELSE ()
    SET(LUAJIT_LIBDIR ${LUAJIT_LIBDIR}/x86)
ENDIF ()

IF (APPLE)
    SET(LUAJIT_LIBNAME "lua51.a")
ELSEIF (CMAKE_COMPILER_IS_GNUCXX)
    SET(LUAJIT_LIBNAME "lua51")
ELSE ()
    SET(LUAJIT_LIBNAME "lua51")
ENDIF ()

FIND_PATH(LUAJIT_INCLUDE_DIR "lua.h"
    PATHS "${CMAKE_SOURCE_DIR}/Source/Dependencies/luaJIT")

FIND_LIBRARY(LUAJIT_LIBRARY ${LUAJIT_LIBNAME}
    PATHS "${CMAKE_SOURCE_DIR}/Source/Dependencies/luaJIT"
    PATH_SUFFIXES "lib/${LUAJIT_LIBDIR}")

#Once one of the calls succeeds the result variable will be set and stored in the cache so that no call will search again.

IF (LUAJIT_LIBRARY AND LUAJIT_INCLUDE_DIR)
    SET(LUAJIT_FOUND "YES")
ELSE()
    SET(LUAJIT_FOUND "NO")
ENDIF()

if (LUAJIT_FOUND)
  message(STATUS "Found LUAJIT: ${LUAJIT_LIBRARY}")
else()
  message(STATUS "Not found LUAJIT in ${LUAJIT_SEARCH_PATHS}")
endif ()
